spring.application.name=HerTrack
#Database Pass X5Mwn36gq7Y1YnRx
#USER ACCESS TOKEN - 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
# Supabase Token - sbp_e7acaf99414b239f9a0da1b649dca33e3e542e3a
spring.ai.huggingface.chat.api-key=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
spring.ai.huggingface.chat.url=https://router.huggingface.co/hf-inference/models/google/flan-t5-large/v1/chat/completions
spring.datasource.url=jdbc:postgresql://db.nzhswtgcvgvfzmsoqpkm.supabase.co:6543/postgres?sslmode=require

spring.datasource.username=postgres
spring.datasource.password=X5Mwn36gq7Y1YnRx
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

#spring.datasource.username=postgres
#spring.datasource.password=XMkSvrBU3J1EWsyp
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

