spring.application.name=HerTrack
spring.ai.huggingface.chat.api-key=KEY
spring.ai.huggingface.chat.url=https://router.huggingface.co/hf-inference/models/google/flan-t5-large/v1/chat/completions

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/hertrack
spring.datasource.username=root
spring.datasource.password=test



# spring.datasource.url=jdbc:postgresql://db.ujejotjraphdmgwatkgb.supabase.co:6543/postgres?sslmode=require
#spring.datasource.username=postgres
#spring.datasource.password=4mWPrO2EVzh1mkTy
#spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings for schema auto-generation (use 'update' or 'validate' in production)
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.show-sql=true

# HikariCP Connection Pool Settings
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.idle-timeout=600000

# Logging levels for debugging
#logging.level.com.zaxxer.hikari=DEBUG
#logging.level.org.hibernate=DEBUG
#logging.level.org.springframework.jdbc=DEBUG


